# Generated by Django 5.0.7 on 2024-07-29 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def fix_invalid_foreign_keys(apps, schema_editor):
    ToDo = apps.get_model('todo', 'ToDo')
    ToDo.objects.filter(user_id=1).delete()




class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(fix_invalid_foreign_keys),
        
        migrations.AlterField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
